

CREATE TABLE [dbo].[CarsContractPaid](
	[ID] [BIGINT] IDENTITY(1,1) NOT NULL,
	[ContractID] [BIGINT] NULL,
	[ContractType] [NVARCHAR](50) NULL,
	[ValuePaid] [FLOAT] NULL,
	[DatePaid] [DATE] NULL,
	[JournalNO] [NVARCHAR](50) NULL,
	[QestID] [BIGINT] NULL,
 CONSTRAINT [PK_CarsContractPaid] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


