

CREATE TABLE [dbo].[Stores_Consumer](
	[GardID] [BIGINT] NOT NULL,
	[ScanDate] [DATE] NULL,
	[StoreID] [INT] NULL,
	[ProunchID] [INT] NULL,
	[COMP_ID] [INT] NULL,
 CONSTRAINT [PK_Stores_Consumer] PRIMARY KEY CLUSTERED 
(
	[GardID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


