 
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[collateral](
	[ID] [BIGINT] NOT NULL,
	[Collateral_AR] [NVARCHAR](150) NULL,
	[Collateral_EN] [NVARCHAR](150) NULL,
 CONSTRAINT [PK_collateral] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


