 

CREATE TABLE [dbo].[BalanceSheet](
	[Net_fixed_assets] [FLOAT] NULL,
	[Net_fixed_assets2] [FLOAT] NULL,
	[Investments_Sister_Companies] [FLOAT] NULL,
	[Investments_Sister_Companies2] [FLOAT] NULL,
	[Projects_under_implementation] [FLOAT] NULL,
	[Projects_under_implementation2] [FLOAT] NULL,
	[OthrAssets] [FLOAT] NULL,
	[OthrAssets2] [FLOAT] NULL,
	[Total_Fixed_Assets] [FLOAT] NULL,
	[Total_Fixed_Assets2] [FLOAT] NULL,
	[Cash] [FLOAT] NULL,
	[Cash2] [FLOAT] NULL,
	[Customers] [FLOAT] NULL,
	[Customers2] [FLOAT] NULL,
	[advance_payments] [FLOAT] NULL,
	[advance_payments2] [FLOAT] NULL,
	[Notes_Receivable] [FLOAT] NULL,
	[Notes_Receivable2] [FLOAT] NULL,
	[Stores] [FLOAT] NULL,
	[Stores2] [FLOAT] NULL,
	[Total_Assets] [FLOAT] NULL,
	[Total_Assets2] [FLOAT] NULL,
	[Supplires] [FLOAT] NULL,
	[Supplires2] [FLOAT] NULL,
	[Bankque] [FLOAT] NULL,
	[Bankque2] [FLOAT] NULL,
	[Short_Loan] [FLOAT] NULL,
	[Short_Loan2] [FLOAT] NULL,
	[Annual_due] [FLOAT] NULL,
	[Annual_due2] [FLOAT] NULL,
	[Other_Credit] [FLOAT] NULL,
	[Other_Credit2] [FLOAT] NULL,
	[Allocations] [FLOAT] NULL,
	[Allocations2] [FLOAT] NULL,
	[Total_Obligations] [FLOAT] NULL,
	[Total_Obligations2] [FLOAT] NULL,
	[Working_Capital] [FLOAT] NULL,
	[Working_Capital2] [FLOAT] NULL,
	[Total_Investment] [FLOAT] NULL,
	[Total_Investment2] [FLOAT] NULL,
	[Payed_Capital] [FLOAT] NULL,
	[Payed_Capital2] [FLOAT] NULL,
	[Reserves] [FLOAT] NULL,
	[Reserves2] [FLOAT] NULL,
	[Profit_Or_loss_Past] [FLOAT] NULL,
	[Profit_Or_loss_Past2] [FLOAT] NULL,
	[Profit_Or_loss] [FLOAT] NULL,
	[Profit_Or_loss2] [FLOAT] NULL,
	[Total_Equity] [FLOAT] NULL,
	[Total_Equity2] [FLOAT] NULL,
	[Long_obligations] [FLOAT] NULL,
	[Long_obligations2] [FLOAT] NULL,
	[Long_Loan] [FLOAT] NULL,
	[Long_Loan2] [FLOAT] NULL,
	[Sister_Loan] [FLOAT] NULL,
	[Sister_Loan2] [FLOAT] NULL,
	[Other_Obligations] [FLOAT] NULL,
	[Other_Obligations2] [FLOAT] NULL,
	[Total_Equity_Obligations] [FLOAT] NULL,
	[Total_Equity_Obligations2] [FLOAT] NULL
) ON [PRIMARY]

GO


