
CREATE TABLE [dbo].[ShipingBill]
    (
      [ShipingID] [BIGINT] NOT NULL ,
      [Shiping_Bill_Date] [DATE] NULL ,
      [Expected_date_arrival] [DATE] NULL ,
      [Actual_arrival_date] [DATE] NULL ,
      [Shipping_date] [DATE] NULL ,
      [ShippingPortID] [BIGINT] NULL ,
      [Place_Shipping] [NVARCHAR](50) NULL ,
      [DeliveryNO] [NVARCHAR](50) NULL ,
      [Delivery_Date] [DATE] NULL ,
      [Customs_Declaration] [NVARCHAR](50) NULL ,
      [CustomsDeclarationdate] [DATE] NULL ,
      [Numberportservices] [NVARCHAR](50) NULL ,
      [DateServives] [DATE] NULL ,
      [Guarantee_check] [NVARCHAR](50) NULL ,
      [Insurance] [NVARCHAR](50) NULL ,
      [Customs_Duties] [DECIMAL](18, 2) NULL ,
      [DateofPayment] [DATE] NULL ,
      [ContainerType] [NCHAR](10) NULL ,
      [ContainerKind] [NVARCHAR](30) NULL ,
      [Container_Size] [NVARCHAR](20) NULL ,
      [Other_Truck_note] [NVARCHAR](50) NULL ,
      [Quantity] [INT] NULL ,
      [Exemption] [DECIMAL](18, 2) NULL ,
      [Storage_Fees] [DECIMAL](18, 2) NULL ,
      [Shipping_Cost] [DECIMAL](18, 2) NULL ,
      [Wages_discharge] [DECIMAL](18, 2) NULL ,
      [Bill] [BIT] NULL ,
      [Certificate_Origin] [BIT] NULL ,
      [Health_Certificate] [BIT] NULL ,
      [SpecificationList] [BIT] NULL ,
      [Other] [BIT] NULL ,
      [Othernote] [NVARCHAR](50) NULL ,
      [BillNumber] [NVARCHAR](20) NULL ,
      [CustomsBondNo] [NVARCHAR](10) NULL ,
      [BillDate] [DATE] NULL ,
      [Amount] [DECIMAL](18, 2) NULL ,
      [NoticeNumber] [NVARCHAR](20) NULL ,
      [NoticeDate] [DATE] NULL ,
      [ExpirationPaymentDate] [DATE] NULL ,
      [Exportingcompany] [NVARCHAR](50) NULL ,
      [General_Notes] [NVARCHAR](MAX) NULL ,
      [Transport_OrderID] [BIGINT] NULL ,
      [ShiperName] [NVARCHAR](150) NULL ,
      [ShiperID] [BIGINT] NULL ,
      [ConsigneeName] [NVARCHAR](150) NULL ,
      [ConsigneeAddress] [NVARCHAR](250) NULL ,
      [ConsigneeID_Iqama] [NVARCHAR](50) NULL ,
      [ConsigneeCity] [NVARCHAR](50) NULL ,
      [ConsigneePhone] [NVARCHAR](50) NULL ,
      [ConsigneeID] [BIGINT] NULL ,
      [BillShiper] [BIT] NULL ,
      [Express] [BIT] NULL ,
      [BillConSiqner] [BIT] NULL ,
      [InsuranceService] [BIT] NULL ,
      [Note] [TEXT] NULL ,
      [ReceiptNo] [NVARCHAR](20) NULL ,
      CONSTRAINT [PK_ShipingBill] PRIMARY KEY CLUSTERED ( [ShipingID] ASC )
        WITH ( PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,
               IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON,
               ALLOW_PAGE_LOCKS = ON ) ON [PRIMARY]
    )
ON  [PRIMARY] TEXTIMAGE_ON [PRIMARY];

GO


