

CREATE VIEW [dbo].[View_ShipingBill]
AS
    SELECT  dbo.customers.customer_name ,
            dbo.Ports.Ports_Name ,
            customers_1.customer_name AS Consignee_Name ,
            dbo.ShipingBill.ShipingID ,
            dbo.ShipingBill.Shiping_Bill_Date ,
            dbo.ShipingBill.Expected_date_arrival ,
            dbo.ShipingBill.Actual_arrival_date ,
            dbo.ShipingBill.Shipping_date ,
            dbo.ShipingBill.ShippingPortID ,
            dbo.ShipingBill.Place_Shipping ,
            dbo.ShipingBill.DeliveryNO ,
            dbo.ShipingBill.Delivery_Date ,
            dbo.ShipingBill.Customs_Declaration ,
            dbo.ShipingBill.CustomsDeclarationdate ,
            dbo.ShipingBill.Numberportservices ,
            dbo.ShipingBill.DateServives ,
            dbo.ShipingBill.Guarantee_check ,
            dbo.ShipingBill.Insurance ,
            dbo.ShipingBill.Customs_Duties ,
            dbo.ShipingBill.DateofPayment ,
            dbo.ShipingBill.ContainerType ,
            dbo.ShipingBill.ContainerKind ,
            dbo.ShipingBill.Container_Size ,
            dbo.ShipingBill.Other_Truck_note ,
            dbo.ShipingBill.Quantity ,
            dbo.ShipingBill.Exemption ,
            dbo.ShipingBill.Storage_Fees ,
            dbo.ShipingBill.Shipping_Cost ,
            dbo.ShipingBill.Wages_discharge ,
            dbo.ShipingBill.Bill ,
            dbo.ShipingBill.Certificate_Origin ,
            dbo.ShipingBill.Health_Certificate ,
            dbo.ShipingBill.SpecificationList ,
            dbo.ShipingBill.Other ,
            dbo.ShipingBill.Othernote ,
            dbo.ShipingBill.BillNumber ,
            dbo.ShipingBill.CustomsBondNo ,
            dbo.ShipingBill.BillDate ,
            dbo.ShipingBill.Amount ,
            dbo.ShipingBill.NoticeNumber ,
            dbo.ShipingBill.NoticeDate ,
            dbo.ShipingBill.ExpirationPaymentDate ,
            dbo.ShipingBill.Exportingcompany ,
            dbo.ShipingBill.General_Notes ,
            dbo.ShipingBill.Transport_OrderID ,
            dbo.ShipingBill.ShiperName ,
            dbo.ShipingBill.ShiperID ,
            dbo.ShipingBill.ConsigneeName ,
            dbo.ShipingBill.ConsigneeAddress ,
            dbo.ShipingBill.ConsigneeID_Iqama ,
            dbo.ShipingBill.ConsigneeCity ,
            dbo.ShipingBill.ConsigneePhone ,
            dbo.ShipingBill.ConsigneeID ,
            dbo.ShipingBill.BillShiper ,
            dbo.ShipingBill.Express ,
            dbo.ShipingBill.BillConSiqner ,
            dbo.ShipingBill.InsuranceService ,
            dbo.ShipingBill.Note ,
            dbo.customers.address ,
            dbo.customers.phone ,
            dbo.customers.fax ,
            dbo.customers.mobile ,
            dbo.customers.ID_Number
    FROM    dbo.customers AS customers_1
            INNER JOIN dbo.customers
            INNER JOIN dbo.ShipingBill
            INNER JOIN dbo.Ports ON dbo.ShipingBill.ShippingPortID = dbo.PORTS.PortsID ON dbo.customers.Customer_id = dbo.ShipingBill.ShiperID ON customers_1.Customer_id = dbo.ShipingBill.ConsigneeID;

GO
