 

CREATE TABLE [dbo].[Documentary_of_Extend](
	[ID] [BIGINT] NOT NULL,
	[Letter_ID] [INT] NULL,
	[Collateral_NO] [NVARCHAR](50) NULL,
	[Notes] [NVARCHAR](MAX) NULL,
	[Date_Strat] [DATE] NULL,
	[Date_End] [DATE] NULL,
	[commission] [FLOAT] NULL,
 CONSTRAINT [PK_Documentary_of_Extend] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO


