 

CREATE TABLE [dbo].[Signed](
	[ID] [BIGINT] IDENTITY(1,1) NOT NULL,
	[Action_ID] [INT] NULL,
	[TagID] [INT] NULL,
	[CaseID] [INT] NULL,
	[Authorized] [NVARCHAR](150) NULL,
	[UserID] [BIGINT] NULL,
	[Status] [BIT] NULL,
	[Notes] [NVARCHAR](MAX) NULL,
	[Date] [DATE] NULL,
	[Time] [TIME](7) NULL,
 CONSTRAINT [PK_Signed] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [dbo].[Signed] ADD  CONSTRAINT [DF_Signed_Status]  DEFAULT ((0)) FOR [Status]
GO


