 
CREATE TABLE [dbo].[Target_Omola](
	[ID] [INT] IDENTITY(1,1) NOT NULL,
	[MandopID] [INT] NULL,
	[ActPersent] [FLOAT] NULL,
	[DuePercent] [FLOAT] NULL,
 CONSTRAINT [PK_Target_Omola] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


