

CREATE TABLE [dbo].[ItemSide2](
	[SideID] [INT] IDENTITY(1,1) NOT NULL,
	[ItemCode] [BIGINT] NULL,
	[SideName] [NVARCHAR](150) NULL,
 CONSTRAINT [PK_ItemSide2] PRIMARY KEY CLUSTERED 
(
	[SideID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


