
ALTER TABLE dbo.Groups_Sub ALTER COLUMN subid BIGINT

ALTER TABLE dbo.Items ALTER COLUMN Item_Gro_Id BIGINT

ALTER TABLE dbo.Items ALTER COLUMN Item_Gro_Sub_Id BIGINT

ALTER TABLE dbo.Items ALTER COLUMN Item_Unit_Id BIGINT

ALTER TABLE dbo.Items ALTER COLUMN Item_unit2 BIGINT

ALTER TABLE dbo.Items ALTER COLUMN Item_unit3 BIGINT




