 

CREATE TABLE [dbo].[Final_Ratio_Setting](
	[ID] [INT] IDENTITY(1,1) NOT NULL,
	[FinalMenuID] [INT] NULL,
	[Aaccount_GroupID] [INT] NULL,
	[MethodID] [INT] NULL,
	[MethodTitele] [NVARCHAR](50) NULL,
	[Switch_to_positive] [INT] NULL,
 CONSTRAINT [PK_Final_Ratio_Setting] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


