 
CREATE TABLE [dbo].[Fallow_Lon](
	[LonID] [BIGINT] NOT NULL,
	[InvDate] [DATE] NULL,
	[Ezn] [BIT] NULL,
	[Bill] [BIT] NULL,
	[EmpLon] [BIT] NULL,
	[InvoiceNo] [BIGINT] NULL,
	[ClientID] [BIGINT] NULL,
	[store_name] [NVARCHAR](50) NULL,
	[ActionDate] [DATE] NULL,
 CONSTRAINT [PK_Fallow_Lon] PRIMARY KEY CLUSTERED 
(
	[LonID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


